library(ggplot2)
Drop <- subset(Mattrix_5, Mattrix_5$Type == "Drop Camera")
TPlink <- subset(Mattrix_5, Mattrix_5$Type == "TP Link camera")
Echo <- subset(Mattrix_5, Mattrix_5$Type == "Amazon Echo")
Motion <- subset(Mattrix_5, Mattrix_5$Type == "Wemo Motion Sensor")
Sam <- subset(Mattrix_5, Mattrix_5$Type == "Samsung SmartCam")
Switch <- subset(Mattrix_5, Mattrix_5$Type == "Belkin Wemo Switch")
ggplot(Mattrix_5, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Drop, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Echo, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Motion, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Sam, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Switch, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(TPlink, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Drop, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Echo, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Motion, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Sam, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Switch, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(TPlink, aes(state, fill = Destination)) + geom_bar(position = "stack")
all<- ggplot(Mattrix_5, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Dr <- ggplot(Drop, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Ec <- ggplot(Echo, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Mo <- ggplot(Motion, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Sa <- ggplot(Sam, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Sw <- ggplot(Switch, aes(state, fill = Protocol)) + geom_bar(position = "stack")
TP <- ggplot(TPlink, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Dr2 <- ggplot(Drop, aes(state, fill = Destination)) + geom_bar(position = "stack")
Ec2 <- ggplot(Echo, aes(state, fill = Destination)) + geom_bar(position = "stack")
Mo2 <-ggplot(Motion, aes(state, fill = Destination)) + geom_bar(position = "stack")
Sa2 <- ggplot(Sam, aes(state, fill = Destination)) + geom_bar(position = "stack")
Sw2 <- ggplot(Switch, aes(state, fill = Destination)) + geom_bar(position = "stack")
TP2 <- ggplot(TPlink, aes(state, fill = Destination)) + geom_bar(position = "stack")
Prot <- ggplot(Mattrix_5, aes(Type, fill = Protocol)) + geom_bar(position = "stack")
all + ggtitle("Protocols in UDP and TCP in Data")
Dr  + ggtitle("Protocols for Drop Camera")
Ec  + ggtitle("Protocols for Amazon Echo")
Mo  + ggtitle("Protocols for Wemo Motion Sensor")
Sa  + ggtitle("Protocols for Samsung SmartCam")
Sw  + ggtitle("Protocols for Belkin Wemo Switch")
TP  + ggtitle("Protocols for TP Link camera")
Dr2 + ggtitle("Destination IP for Drop Camera")
Ec2 + ggtitle("Destination IP for Amazon Echo")
Mo2 + ggtitle("Destination IP for Wemo Motion Sensor")
Sa2 + ggtitle("Destination IP for Samsung SmartCam")
Sw2 + ggtitle("Destination IP for Belkin Wemo Switch")
TP2 + ggtitle("Destination IP for TP Link camera")
Prot + ggtitle("Protocols for Data Set")