hist(Sept29th$Source.Port)
hist(Sept29th$Window.size.value)
hist(Sept29th$Destination.Port)
hist(Sept29th$Length)
boxplot(Sept29th$Source.Port)
boxplot(Sept29th$Length)
boxplot(Sept29th$Source.Port)
plot(Sept29th$Time, Sept29th$Source.Port)
plot(Sept29th$Length, Sept29th$Source.Port)
plot(Sept29th$Time, Sept29th$Source.Port)
plot(Sept29th$Time, Sept29th$Window.size.value)
boxplot(Sept29th$Destination.Port)
boxplot(Sept29th$Window.size.value)