levels(Sept29th$Protocol)
levels(Sept29th$Source.1)
levels(Sept29th$Source)
glimpse(Sept29th)
Sept29th_SSDP <- Sept29th %>% filter(grepl("SSDP", Protocol))
summary(Sept29th_SSDP$Length)
summary(Sept29th_SSDP$Info)
summary(Sept29th_SSDP$Source)
summary(Sept29th_SSDP$Destination)
Sept29th_dns <- Sept29th %>% filter(grepl("DNS", Protocol))
summary(Sept29th_dns$Length)
summary(Sept29th_dns$Info)
library(dplyr)
Sept29th_SSDP <- Sept29th %>% filter(grepl("SSDP", Protocol))
summary(Sept29th_SSDP$Length)
summary(Sept29th_SSDP$Info)
summary(Sept29th_SSDP$Source)
summary(Sept29th_SSDP$Destination)
Sept29th_dns <- Sept29th %>% filter(grepl("DNS", Protocol))
summary(Sept29th_dns$Length)
summary(Sept29th_dns$Info)
summary(Sept29th_dns$Source)
summary(Sept29th_dns$Destination)
Sept29th_TLS <- Sept29th %>% filter(grepl("TLSv1.2", Protocol))
summary(Sept29th_TLS$Length)
summary(Sept29th_TLS$Info)
summary(Sept29th_TLS$Source)
summary(Sept29th_TLS$Destination)
levels(Sept29th$Protocol)
tail(sort(summary(Sept29th$Protocol)),44)
tail(sort(summary(Sept29th$Protocol)),44)
Sept29th_EAPOL <- Sept29th %>% filter(grepl("EAPOL", Protocol))
summary(Sept29th_EAPOL$Length)
summary(Sept29th_EAPOL$Info)
summary(Sept29th_EAPOL$Source)
summary(Sept29th_EAPOL$Destination)
Sept29th_UDPENCAP <- Sept29th %>% filter(grepl("UDPENCAP", Protocol))
summary(Sept29th_UDPENCAP$Length)
summary(Sept29th_UDPENCAP$Info)
summary(Sept29th_UDPENCAP$Source)
summary(Sept29th_UDPENCAP$Destination)
Sept29th_DHCP <- Sept29th %>% filter(grepl("DHCP", Protocol))
summary(Sept29th_DHCP$Info)
summary(Sept29th_DHCP$Length)
summary(Sept29th_DHCP$Source)
summary(Sept29th_DHCP$Destination)
Sept29th_UDT <- Sept29th %>% filter(grepl("UDT", Protocol))
summary(Sept29th_UDT$Length)
summary(Sept29th_UDT$Info)
summary(Sept29th_UDT$Source)
summary(Sept29th_UDT$Destination)
strange <- Sept29th %>% filter(grepl("129.94.5.88", Destination))
Sept29th_NTP <- Sept29th %>% filter(grepl("NTP", Protocol))
summary(Sept29th_NTP$Length)
summary(Sept29th_NTP$Info)
summary(Sept29th_NTP$Source)
summary(Sept29th_NTP$Destination)
Sept29th_ICMP <- Sept29th %>% filter(grepl("ICMP", Protocol))
summary(Sept29th_ICMP$Length)
summary(Sept29th_NTP$Info)
summary(Sept29th_ICMP$Info)
summary(Sept29th_ICMP$Source)
summary(Sept29th_ICMP$Destination)
Sept29th_IGMPv2 <- Sept29th %>% filter(grepl("IGMPv2", Protocol))
summary(Sept29th_IGMPv2$Length)
summary(Sept29th_IGMPv2$Info)
summary(Sept29th_IGMPv2$Source)
summary(Sept29th_IGMPv2$Destination)
Sept29th_HTTP <- Sept29th %>% filter(grepl("HTTP", Protocol))
summary(Sept29th_HTTP$Length)
summary(Sept29th_HTTP$Info)
summary(Sept29th_HTTP$Source)
summary(Sept29th_HTTP$Destination)
Sept29th_UDP <- Sept29th %>% filter(grepl("UDP", Protocol))
summary(Sept29th_UDP$Length)
summary(Sept29th_UDP$Info)
summary(Sept29th_UDP$Source)
summary(Sept29th_UDP$Destination)
Sept29th_TLSv1 <- Sept29th %>% filter(grepl("TLSv1", Protocol))
summary(Sept29th_TLSv1$Length)
summary(Sept29th_TLSv1$Info)
summary(Sept29th_TLSv1$Source)
summary(Sept29th_TLSv1$Destination)
Sept29th_TCP <- Sept29th %>% filter(grepl("TCP", Protocol))
summary(Sept29th_TCP$Length)
summary(Sept29th_TCP$Info)
summary(Sept29th_TCP$Source)
summary(Sept29th_TCP$Destination)
Sept29th_ht_xm <- Sept29th %>% filter(grepl("HTTP/XML", Protocol))
summary(Sept29th_ht_xm$Length)
summary(Sept29th_ht_xm$Info)
summary(Sept29th_ht_xm$Source)
summary(Sept29th_ht_xm$Destination)


