Sept29th <- read.csv(file.choose( ))
dim(Sept29th)
class(Sept29th)
str(Sept29th)
summary(Sept29th)
dim(Sept29th)
str(Sept29th)
summary(Sept29th)
library(dplyr)
glimpse(Sept29th)
head(Sept29th,n=15)
tail(Sept29th,n=15)
levels(Sept29th$Protocol)
summary(Sept29th$Source.1)
summary(Sept29th$Protocols)
summary(Sept29th$Protocol)
summary(Sept29th$Source)
summary(Sept29th$Destination)
head(summary(Sept29th$Source))
head(summary(Sept29th$Source.1))
head(summary(Sept29th$Destination))
head(summary(Sept29th$Info))
tail(sort(summary(Sept29th$Protocol)),44)
alpha_Sept29th<- Sept29th %>% filter(grepl("[a-z]", Source))
num_Sept29th<- Sept29th %>% filter(!grepl("[a-z]", Source))
DNS_Sept29th<- Sept29th %>% filter(grepl("DNS", Source))
TLS_Sept29th<- Sept29th %>% filter(grepl("TLSv1.2", Protocol))
SSDP_Sept29th<- Sept29th %>% filter(grepl("SSDP", Protocol))
num_Sept29th_sort<-arrange(num_Sept29th, Source.1,Source, Protocol)
count(num_Sept29th, Protocol)
cS1SDPInS29th <- count(num_Sept29th, Source.1, Source, Destination, Protocol, Info)
library(mosaic)
tally(~Protocol, data = num_Sept29th, format = "percent")
tally(~Source.1, data = num_Sept29th, format = "percent")
bargraph(~Protocol, data =  cS1SDPInS29th, format = "proportion")
bargraph(~Protocol, data =  num_Sept29th, format = "proportion")
bargraph(~Protocol, data =  Sept29th, format = "proportion")
tally(~Source.1, data = Sept29th, format = "percent")
bargraph(~Source.1, data =  Sept29th, format = "proportion")
bargraph(~Source.1, data =  num_Sept29th, format = "proportion")
bargraph(~Source.1, data =  alph_Sept29th, format = "proportion")
bargraph(~Source.1, data =  alpha_Sept29th, format = "proportion")
bargraph(~Protocol, data =  alpha_Sept29th, format = "proportion")
kruskal.test(x = Sept29th$Source.Port, g = as.factor(Sept29th$Source))
kruskal.test(x = Sept29th$Length, g = as.factor(Sept30th$Source))
kruskal.test(x = Sept29th$Length, g = as.factor(Sept29th$Source))
kruskal.test(x = Sept29th$Window.size.value, g = as.factor(Sept29th$Source))
kruskal.test(x = Sept29th$Time.to.live, g = as.factor(Sept29th$Source))
kruskal.test(x = Sept29th$Time.to.live, g = as.factor(Sept29th$Source))
print(chisq.test(table(Sept29th$Source, Sept29th$Source.1)))
print(chisq.test(table(Sept29th$Source, Sept29th$Protocol)))
print(chisq.test(table(Sept29th$Source, Sept29th$Info)))
levels(Sept29th$Protocol)
levels(Sept29th$Source.1)
levels(Sept29th$Source)




