Sept30th<-read.csv(file.choose())
View(Sept30th)
dim(Sept30th)
class(Sept30th)
names(Sept30th)
str(Sept30th)
summary(Sept30th)
library(dplyr)
glimpse(Sept30th)
head(Sept30th,n=15)
tail(Sept30th,n=15)
levels(Sept30th$Protocol)
levels(Sept30th$Source)
levels(Sept30th$Source.1)
levels(Sept30th$Destination)
summary(Sept30th$Source.1)
summary(Sept30th$Protocol)
summary(Sept30th$Source)
summary(Sept30th$Destination)
head(summary(Sept30th$Source))
head(summary(Sept30th$Source.1))
head(summary(Sept30th$Destination))
head(summary(Sept30th$Info))
tail(sort(summary(Sept30th$Protocol)),10)
library(dplyr)
alpha_Sept30th<- Sept30th %>% filter(grepl("[a-z]", Source))
num_Sept30th<- Sept30th %>% filter(!grepl("[a-z]", Source))
DNS_Sept30th<- Sept30th %>% filter(grepl("DNS", Source))
DNS_Sept30th<- num_Sept30th %>% filter(grepl("DNS", Protocol))
TLS_Sept30th<- num_Sept30th %>% filter(grepl("TLSv1.2", Protocol))
SSDP_Sept30th<- num_Sept30th %>% filter(grepl("SSDP", Protocol))
num_Sept30th_sort<-arrange(num_Sept30th, Source.1,Source, Protocol)
View(num_Sept30th_sort)
View(num_Sept30th)
View(num_Sept30th_sort)
count(num_Sept30th, Protocol)
cS1SDPInS30th <- count(num_Sept30th, Source.1, Source, Destination, Protocol, Info)
View(cS1SDPInS30th)
library(mosaic)
tally(~Protocol, data = num_Sept30th, format = "percent")
tally(~Source.1, data = num_Sept30th, format = "percent")
bargraph(~Protocol, data =  cS1SDPInS30th, format = "proportion")
bargraph(~Protocol, data =  num_Sept30th, format = "proportion")
bargraph(~Protocol, data =  Sept30th, format = "proportion")
tally(~Source.1, data = Sept30th, format = "percent")
bargraph(~Source.1, data =  Sept30th, format = "proportion")
bargraph(~Source.1, data =  num_Sept30th, format = "proportion")
bargraph(~Source.1, data =  alph_Sept30th, format = "proportion")
bargraph(~Source.1, data =  alpha_Sept30th, format = "proportion")
bargraph(~Protocol, data =  alpha_Sept30th, format = "proportion")
kruskal.test(x = Sept30th$Source.Port, g = as.factor(Sept30th$Source))
kruskal.test(x = Sept30th$Length, g = as.factor(Sept30th$Source))
kruskal.test(x = Sept30th$Window.size.value, g = as.factor(Sept30th$Source))
kruskal.test(x = Sept30th$Time.to.live, g = as.factor(Sept30th$Source))
print(chisq.test(table(Sept30th$Source, Sept30th$Source.1)))
print(chisq.test(table(Sept30th$Source, Sept30th$Protocol)))
print(chisq.test(table(Sept30th$Source, Sept30th$Info)))
