Sept30b <- read.csv(file.choose( ))
library (dplyr)
library(caret)
library(ranger)
alpa_Sept30b <- Sept30b %>% filter(grepl("[a-z]", Source))
num_Sept30b <- Sept30b %>% filter(!grepl("[a-z]", Source))
Stateless<- subset(num_Sept30b, is.na(Source.Port))
Stateful<- subset(num_Sept30b, !is.na(Source.Port))
Stateful$state <- 1
Stateless$state <- 0
N_Sept30b <<- rbind(Stateful, Stateless)
nSept30b_go1 <- filter(N_Sept30b, Source != "::" )
nSept30b_go2 <- filter(nSept30b_go1, Source != "0.0.0.0" )
nSept30b_go3 <- filter(nSept30b_go2, Source != "8.8.8.8" )
Mattrix_2 <- subset(nSept30b_go3, Source %in% c("192.168.1.249", "192.168.1.106", "192.168.1.223", "192.168.1.193", "192.168.1.143" ,"192.168.1.240") )
Mattrix_3 <- subset(Mattrix_2, select = -c(Source.Port, Destination.Port, Window.size.value))
library(ggplot2)
ggplot(Mattrix_3, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Mattrix_3, aes(state, fill = Destination.1)) + geom_bar(position = "stack")
ggplot(Mattrix_3, aes(state, fill = Protocol)) + geom_bar(position = "dodge")
ggplot(Mattrix_3, aes(state, fill = Destination.1)) + geom_bar(position = "dodge")
ggplot(Mattrix_3, aes(Protocol)) + geom_bar() + facet_grid(state~.)
ggplot(Mattrix_3, aes(Destination.1)) + geom_bar() + facet_grid(state~.)