Sept30b <- read.csv(file.choose( ))
library (dplyr)
num_Sept30b <- Sept30b %>% filter(!grepl("[a-z]", Source))
alpa_Sept30b <- Sept30b %>% filter(grepl("[a-z]", Source))
Stateless<- subset(num_Sept30b, is.na(Source.Port))
Stateful<- subset(num_Sept30b, !is.na(Source.Port))
Stateful$state <- 1
Stateless$state <- 0
N_Sept30b <<- rbind(Stateful, Stateless)
glimpse(N_Sept30b)
plot(N_Sept30b$Protocol, N_Sept30b$state)
plot(N_Sept30b$Source.Port, N_Sept30b$state)
boxplot(N_Sept30b$Protocol, N_Sept30b$state)
boxplot(N_Sept30b$state.N_Sept30b$Protocol)
bwplot(N_Sept30b$State.N_Sept30b$Protocol)
bwplot(N_Sept30b$Protocol, N_Sept30b$state)
nSept30b_go1 <- filter(N_Sept30b, Source != "::" )
nSept30b_go2 <- filter(N_Sept30b, Source != "0.0.0.0" )
nSept30b_go3 <- filter(N_Sept30b, Source != "8.8.8.8" )
fair <- lm(Window.size.value ~ Source, data = nSept30b_go3)
summary(fair)
fairer <- lm(Window.size.value ~ Source.Port, data = nSept30b_go3)
summary(fairer)
fairest <- lm(Window.size.value ~ Protocol + Source, data = nSept30b_go3)
summary(fairest)
nextfair <- lm(Length ~ Protocol + Source, data = nSept30b_go3)
summary(nextfair)
fairly <- lm(Length ~ state, data = nSept30b_go3)
summary(fairly)
fairlly <- lm(Window.size.value ~ state, data = nSept30b_go3)
summary(fairlly)
fairrly <- lm(Length ~ state + Protocol, data = nSept30b_go3)
summary(fairrly)
ffairrlly <- lm(state ~ Source, data = nSept30b_go3)
summary(ffairrlly)
nextfairest <- lm(Length ~ Source, data = nSept30b_go3)
summary(nextfairest)
rparter <- rpart(Window.size.value ~ Protocol, data = nSept30b_go3)
summary(rparter)
fmodel(fairer)
coef(summary(fairest))
anova(fairest)
whatif<- lm(Window.size.value ~ Protocol + Length, data = nSept30b_go3)
summary(whatif)
whynot<- lm(Window.size.value ~ Source + Length, data = nSept30b_go3)
summary(whynot)
whatthe<- lm(Window.size.value ~ Length, data = nSept30b_go3)
summary(whatthe)
AIC(whatthe)
AIC(whynot)
AIC(whatif)
AIC(fairer)
AIC(fairest)
hmmm<- lm(Source ~ Window.size.value, data = nSept30b_go3)
hmph<- lm(Source.Port ~ Source, data = nSept30b_go3)
summary(hmph)
AIC(hmph)
long<- lm(Length ~ Source, data = nSept30b_go3)
long<- lm(Length ~ Protocol, data = nSept30b_go3)
summary(long)
nextfairests <- glm(Length ~ Source, data = nSept30b_go3)
Sept29th <- read.csv(file.choose( ))
nextfairest <- lm(Length ~ Source, data = nSept30b_go3)
summary(nextfairest)
mostfair <- data.frame(summary(nextfairest)$coef[summary(nextfairest)$coef[,4] <= .05, 4])
nextfair <- glm(Length ~ Source, data = nSept30b_go3)
close <- hoslem.test(nextfair$Length, fitted(nextfair))
close <- hoslem.test(nextfair$Length, fitted(nextfair), g = 10)
nextprot <- lm(Length ~ Protocol, data = nSept30b_go3)
data.frame(summary(nextfairest)$coef[summary(nextfairest)$coef[,4] <= .05, 4])
data.frame(summary(nextprot)$coef[summary(nextprot)$coef[,4] <= .05, 4])
nextprot_a <- lm(Length ~ Protocol, data = Stateful)
nextprot_b <- lm(Length ~ Protocol, data = Stateless)
data.frame(summary(nextprot)$coef[summary(nextprot)$coef[,4] < 2e-16, 4])
data.frame(summary(nextfairest)$coef[summary(nextfairest)$coef[,4] < 2e-16, 4])
predict(lm(Length ~ Source, data = nSept30b_go3))
confint(nextfairest)
confint(nextprot)
sigma(nextfairest)
sigma(nextprot)
find <- predict(nextfairest, nSept30b_go3, interval="prediction", level=0.95)
hist(Sept29th$Source.Port)
hist(Sept29th$Window.size.value)
hist(Sept29th$Destination.Port)
hist(Sept29th$Length)
boxplot(Sept29th$Source.Port)
boxplot(Sept29th$Length)
plot(Sept29th$Time, Sept29th$Source.Port)
boxplot(Sept29th$Source.Port)
plot(Sept29th$Length, Sept29th$Source.Port)
plot(Sept29th$Length, Sept29th$Source.Port)
plot(Sept29th$Time, Sept29th$Source.Port)
plot(Sept29th$Time, Sept29th$Window.size.value)
alpa_Sept29b <- Sept20b %>% filter(grepl("[a-z]", Source))
num_Sept29b <- Sept29b %>% filter(!grepl("[a-z]", Source))
Stateles29s<- subset(num_Sept29b, is.na(Source.Port))
Stateful29<- subset(num_Sept29b, !is.na(Source.Port))
Stateful29$state <- 1
Stateless29$state <- 0
N_Sept29b <<- rbind(Stateful29, Stateles29s)
nSept29b_go1 <- filter(N_Sept29b, Source != "::" )
nSept29b_go2 <- filter(N_Sept29b, Source != "0.0.0.0" )
nSept29b_go3 <- filter(N_Sept30b, Source != "8.8.8.8" )
again <- lm(Length ~ Source, data = nSept29b_go3)
summary(again)
more_again <- data.frame(summary(again)$coef[summary(again)$coef[,4] < 2e-16, 4])
data.frame(summary(again)$coef[summary(again)$coef[,4] < 2e-16, 4])
second <- lm(Length ~ Protocol, data = nSept29b_go3)
data.frame(summary(second)$coef[summary(second)$coef[,4] < 2e-16, 4])
plot(again)
anova(again)
anova(second)
anova(nextfairest)
anova(nextprot)
nSept29b_go3n <- select(nSept29b_go3, -Source.Port, -Destination.Port,-Window.size.value )
nextfairy <- glm(Length ~ Source, data = nSept29b_go3n)
library(glmnet)
library(broom)
library(tidyverse)
x <- nSept30b_go3 %>% select(Protocol,Source) %>% data.matrix()
lambdas <- 10^seq(3, -2, by = -.1)
y <- nSept30b_go3$Length
fit <- glmnet(x, y, alpha = 0, lambda = lambdas)
summary(fit)
cv_fit <- cv.glmnet(x, y, alpha = 0, lambda = lambdas)
plot(cv_fit)
opt_lambda <- cv_fit$lambda.min
opt_lambda
fit <- cv_fit$glmnet.fit
summary(fit)
y_predicted <- predict(fit, s = opt_lambda, newx = x)
sst <- sum((y - mean(y))^2)
sse <- sum((y_predicted - y)^2)
rsq <- 1 - sse / sst
rsq















