Drop <- subset(Mattrix_5, Mattrix_5$Type == "Drop Camera")
TPlink <- subset(Mattrix_5, Mattrix_5$Type == "TP link camera")
Echo <- subset(Mattrix_5, Mattrix_5$Type == "Amazon Echo")
Motion <- subset(Mattrix_5, Mattrix_5$Type == "Wemo Motion Sensor")
Sam <- subset(Mattrix_5, Mattrix_5$Type == "Samsung SmartCam")
Switch <- subset(Mattrix_5, Mattrix_5$Type == "Belkin Wemo Switch")
library(ggplot2)
ggplot(Mattrix_5, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Drop, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Echo, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Motion, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Sam, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Switch, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(TPlink, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Drop, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Echo, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Motion, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Sam, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Switch, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(TPlink, aes(state, fill = Destination)) + geom_bar(position = "stack")
