Sept30b <- read.csv(file.choose( ))
library (dplyr)
library(caret)
library(ggplot2)
alpa_Sept30b <- Sept30b %>% filter(grepl("[a-z]", Source))
num_Sept30b <- Sept30b %>% filter(!grepl("[a-z]", Source))
Stateless<- subset(num_Sept30b, is.na(Source.Port))
Stateful<- subset(num_Sept30b, !is.na(Source.Port))
Stateful$state <- 1
Stateless$state <- 0
N_Sept30b <<- rbind(Stateful, Stateless)
nSept30b_go1 <- filter(N_Sept30b, Source != "::" )
nSept30b_go2 <- filter(nSept30b_go1, Source != "0.0.0.0" )
nSept30b_go3 <- filter(nSept30b_go2, Source != "8.8.8.8" )
Mattrix_2 <- subset(nSept30b_go3, Source %in% c("192.168.1.249", "192.168.1.106", "192.168.1.223", "192.168.1.193", "192.168.1.143" ,"192.168.1.240") )
Mattrix_3 <- subset(Mattrix_2, select = -c(Source.Port, Destination.Port, Window.size.value))
Mattrix_4 <- subset(Mattrix_3, Protocol %in% c("CLASSIC-STUN", "DNS", "HTTP", "HTTP/XML", "ICMP" ,"Omni-Path" ,"SSDP","STUN","TCP","TLSv1","TLSv1.2","UDP","UDT") )
Mattrix_5 = subset(Mattrix_4, select = -c(No.,Info ))
Drop <- subset(Mattrix_5, Mattrix_5$Type == "Drop Camera")
TPlink <- subset(Mattrix_5, Mattrix_5$Type == "TP link camera")
Echo <- subset(Mattrix_5, Mattrix_5$Type == "Amazon Echo")
Motion <- subset(Mattrix_5, Mattrix_5$Type == "Wemo Motion Sensor")
Sam <- subset(Mattrix_5, Mattrix_5$Type == "Samsung SmartCam")
Switch <- subset(Mattrix_5, Mattrix_5$Type == "Belkin Wemo Switch")
ggplot(Mattrix_5, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Drop, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Echo, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Motion, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Sam, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Switch, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(TPlink, aes(state, fill = Protocol)) + geom_bar(position = "stack")
ggplot(Drop, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Echo, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Motion, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Sam, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(Switch, aes(state, fill = Destination)) + geom_bar(position = "stack")
ggplot(TPlink, aes(state, fill = Destination)) + geom_bar(position = "stack")
