Sept30b <- read.csv(file.choose( ))
library (dplyr)
library(caret)
library(ggplot2)
alpa_Sept30b <- Sept30b %>% filter(grepl("[a-z]", Source))
num_Sept30b <- Sept30b %>% filter(!grepl("[a-z]", Source))
Stateless<- subset(num_Sept30b, is.na(Source.Port))
Stateful<- subset(num_Sept30b, !is.na(Source.Port))
Stateful$state <- 1
Stateless$state <- 0
N_Sept30b <<- rbind(Stateful, Stateless)
nSept30b_go1 <- filter(N_Sept30b, Source != "::" )
nSept30b_go2 <- filter(nSept30b_go1, Source != "0.0.0.0" )
nSept30b_go3 <- filter(nSept30b_go2, Source != "8.8.8.8" )
Mattrix_2 <- subset(nSept30b_go3, Source %in% c("192.168.1.249", "192.168.1.106", "192.168.1.223", "192.168.1.193", "192.168.1.143" ,"192.168.1.240") )
Mattrix_3 <- subset(Mattrix_2, select = -c(Source.Port, Destination.Port, Window.size.value))
Mattrix_3$Type <- NA
Mattrix_3$Type[Mattrix_3$Source.1 == "44:65:0d:56:cc:d3"] <- "Amazon Echo"
Mattrix_3$Type[Mattrix_3$Source.1 == "30:8c:fb:2f:e4:b2"] <- "Drop Camera"
Mattrix_3$Type[Mattrix_3$Source.1 == "ec:1a:59:83:28:11"] <- "Wemo Motion Sensor"
Mattrix_3$Type[Mattrix_3$Source.1 == "f4:f2:6d:93:51:f1"] <- "TP Link camera"
Mattrix_3$Type[Mattrix_3$Source.1 == "00:16:6c:ab:6b:88"] <- "Samsung SmartCam"
Mattrix_3$Type[Mattrix_3$Source.1 == "ec:1a:59:79:f4:89"] <- "Belkin Wemo Switch"
Mattrix_3$Type[Mattrix_3$Source.1 == "44:65:0d:56:cc:d3"] <- "Amazon Echo"
Mattrix_3$state <- as.factor(Mattrix_3$state)
Mattrix_3$Type <- as.factor(Mattrix_3$Type)
Mattrix_4 <- subset(Mattrix_3, Protocol %in% c("CLASSIC-STUN", "DNS", "HTTP", "HTTP/XML", "ICMP" ,"Omni-Path" ,"SSDP","STUN","TCP","TLSv1","TLSv1.2","UDP","UDT") )
Mattrix_5 = subset(Mattrix_4, select = -c(No.,Info ))
Drop <- subset(Mattrix_5, Mattrix_5$Type == "Drop Camera")
TPlink <- subset(Mattrix_5, Mattrix_5$Type == "TP Link camera")
Echo <- subset(Mattrix_5, Mattrix_5$Type == "Amazon Echo")
Motion <- subset(Mattrix_5, Mattrix_5$Type == "Wemo Motion Sensor")
Sam <- subset(Mattrix_5, Mattrix_5$Type == "Samsung SmartCam")
Switch <- subset(Mattrix_5, Mattrix_5$Type == "Belkin Wemo Switch")
all<- ggplot(Mattrix_5, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Dr <- ggplot(Drop, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Ec <- ggplot(Echo, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Mo <- ggplot(Motion, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Sa <- ggplot(Sam, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Sw <- ggplot(Switch, aes(state, fill = Protocol)) + geom_bar(position = "stack")
TP <- ggplot(TPlink, aes(state, fill = Protocol)) + geom_bar(position = "stack")
Dr2 <- ggplot(Drop, aes(state, fill = Destination)) + geom_bar(position = "stack")
Ec2 <- ggplot(Echo, aes(state, fill = Destination)) + geom_bar(position = "stack")
Mo2 <-ggplot(Motion, aes(state, fill = Destination)) + geom_bar(position = "stack")
Sa2 <- ggplot(Sam, aes(state, fill = Destination)) + geom_bar(position = "stack")
Sw2 <- ggplot(Switch, aes(state, fill = Destination)) + geom_bar(position = "stack")
TP2 <- ggplot(TPlink, aes(state, fill = Destination)) + geom_bar(position = "stack")
Prot <- ggplot(Mattrix_5, aes(Type, fill = Protocol)) + geom_bar(position = "stack")
all + ggtitle("Protocols in UDP and TCP in Data")
Dr  + ggtitle("Protocols for Drop Camera")
Ec  + ggtitle("Protocols for Amazon Echo")
Mo  + ggtitle("Protocols for Wemo Motion Sensor")
Sa  + ggtitle("Protocols for Samsung SmartCam")
Sw  + ggtitle("Protocols for Belkin Wemo Switch")
TP  + ggtitle("Protocols for TP Link camera")
Dr2 + ggtitle("Destination IP for Drop Camera")
Ec2 + ggtitle("Destination IP for Amazon Echo")
Mo2 + ggtitle("Destination IP for Wemo Motion Sensor")
Sa2 + ggtitle("Destination IP for Samsung SmartCam")
Sw2 + ggtitle("Destination IP for Belkin Wemo Switch")
TP2 + ggtitle("Destination IP for TP Link camera")
Prot + ggtitle("Protocols for Data Set")