nSept30b_go1 <- filter(N_Sept30b, Source != "::" )
nSept30b_go2 <- filter(nSept30b_go1, Source != "0.0.0.0" )
nSept30b_go3 <- filter(nSept30b_go2, Source != "8.8.8.8" )
nSept30b_go3a <- filter(nSept30b_go3, Source != "NA" )
more <- lm(Length ~ Protocol + Source.Port + Destination.Port + Window.size.value, data = nSept30b_go3a)
morer <- lm(Length ~ Source + Source.Port + Destination.Port + Window.size.value, data = nSept30b_go3a)
sore <- glm(Length ~ Protocol + Source.Port + Destination.Port + Window.size.value, data = nSept30b_go3a)
sorer <- glm(Length ~ Source + Source.Port + Destination.Port + Window.size.value, data = nSept30b_go3a)
Sept29b <- read.csv(file.choose( ))
alpa_Sept29b <- Sept29b %>% filter(grepl("[a-z]", Source))
num_Sept29b <- Sept29b %>% filter(!grepl("[a-z]", Source))
Stateless29<- subset(num_Sept29b, is.na(Source.Port))
Stateful29<- subset(num_Sept29b, !is.na(Source.Port))
Stateful29$state <- 1
Stateless29$state <- 0
N_Sept29b <<- rbind(Stateful29, Stateless29)
nSept29b_go1 <- filter(N_Sept29b, Source != "::" )
nSept29b_go2 <- filter(nSept29b_go1, Source != "0.0.0.0" )
nSept29b_go3 <- filter(nSept29b_go2, Source != "8.8.8.8" )
nSept29b_go3a <- filter(nSept29b_go3, Source != "NA" )
pore <- glm(Length ~ Protocol + Source.Port + Destination.Port + Window.size.value, data = nSept29b_go3a)
porer <- glm(Length ~ Source + Source.Port + Destination.Port + Window.size.value, data = nSept29b_go3a)
sorey <- glm(Length ~ Protocol + Source.Port + Window.size.value, data = nSept30b_go3a)
# not including the Destination Port - PCA
sorery <- glm(Length ~ Source + Source.Port + Window.size.value, data = nSept30b_go3a)
pore <- glm(Length ~ Protocol + Source.Port, data = nSept29b_go3a)
