levels(Sept30th$Protocol)
levels(Sept30th$Source.1)
levels(Sept30th$Source)
glimpse(Sept30th)
View(num_Sept30th)
glimpse(num_Sept30th)
View(alpha_Sept30th)
View(cS1SDPInS30th)
library(dplyr)
Sept30th_SSDP <- Sept30th %>% filter(grepl("SSDP", Protocol))
summary(Sept30th_SSDP$Length)
summary(Sept30th_SSDP$Info)
summary(Sept30th_SSDP$Source)
summary(Sept30th_SSDP$Destination)
Sept30th_dns <- Sept30th %>% filter(grepl("DNS", Protocol))
summary(Sept30th_dns$Length)
summary(Sept30th_dns$Info)
library(dplyr)
Sept30th_SSDP <- Sept30th %>% filter(grepl("SSDP", Protocol))
summary(Sept30th_SSDP$Length)
summary(Sept30th_SSDP$Info)
summary(Sept30th_SSDP$Source)
summary(Sept30th_SSDP$Destination)
Sept30th_dns <- Sept30th %>% filter(grepl("DNS", Protocol))
summary(Sept30th_dns$Length)
summary(Sept30th_dns$Info)
summary(Sept30th_dns$Source)
summary(Sept30th_dns$Destination)
Sept30th_TLS <- Sept30th %>% filter(grepl("TLSv1.2", Protocol))
summary(Sept30th_TLS$Length)
summary(Sept30th_TLS$Info)
summary(Sept30th_TLS$Source)
summary(Sept30th_TLS$Destination)
levels(Sept30th$Protocol)
tail(sort(summary(Sept30th$Protocol)),44)
tail(sort(summary(Sept30th$Protocol)),44)
Sept30th_EAPOL <- Sept30th %>% filter(grepl("EAPOL", Protocol))
summary(Sept30th_EAPOL$Length)
summary(Sept30th_EAPOL$Info)
summary(Sept30th_EAPOL$Source)
summary(Sept30th_EAPOL$Destination)
Sept30th_UDPENCAP <- Sept30th %>% filter(grepl("UDPENCAP", Protocol))
summary(Sept30th_UDPENCAP$Length)
summary(Sept30th_UDPENCAP$Info)
summary(Sept30th_UDPENCAP$Source)
summary(Sept30th_UDPENCAP$Destination)
Sept30th_DHCP <- Sept30th %>% filter(grepl("DHCP", Protocol))
summary(Sept30th_DHCP$Info)
summary(Sept30th_DHCP$Length)
summary(Sept30th_DHCP$Source)
summary(Sept30th_DHCP$Destination)
Sept30th_UDT <- Sept30th %>% filter(grepl("UDT", Protocol))
summary(Sept30th_UDT$Length)
summary(Sept30th_UDT$Info)
summary(Sept30th_UDT$Source)
summary(Sept30th_UDT$Destination)
strange <- Sept30th %>% filter(grepl("129.94.5.88", Destination))
Sept30th_NTP <- Sept30th %>% filter(grepl("NTP", Protocol))
summary(Sept30th_NTP$Length)
summary(Sept30th_NTP$Info)
summary(Sept30th_NTP$Source)
summary(Sept30th_NTP$Destination)
Sept30th_ICMP <- Sept30th %>% filter(grepl("ICMP", Protocol))
summary(Sept30th_ICMP$Length)
summary(Sept30th_NTP$Info)
summary(Sept30th_ICMP$Info)
summary(Sept30th_ICMP$Source)
summary(Sept30th_ICMP$Destination)
Sept30th_IGMPv2 <- Sept30th %>% filter(grepl("IGMPv2", Protocol))
summary(Sept30th_IGMPv2$Length)
summary(Sept30th_IGMPv2$Info)
summary(Sept30th_IGMPv2$Source)
summary(Sept30th_IGMPv2$Destination)
Sept30th_HTTP <- Sept30th %>% filter(grepl("HTTP", Protocol))
summary(Sept30th_HTTP$Length)
summary(Sept30th_HTTP$Info)
summary(Sept30th_HTTP$Source)
summary(Sept30th_HTTP$Destination)
Sept30th_UDP <- Sept30th %>% filter(grepl("UDP", Protocol))
summary(Sept30th_UDP$Length)
summary(Sept30th_UDP$Info)
summary(Sept30th_UDP$Source)
summary(Sept30th_UDP$Destination)
Sept30th_TLSv1 <- Sept30th %>% filter(grepl("TLSv1", Protocol))
summary(Sept30th_TLSv1$Length)
summary(Sept30th_TLSv1$Info)
summary(Sept30th_TLSv1$Source)
summary(Sept30th_TLSv1$Destination)
Sept30th_TCP <- Sept30th %>% filter(grepl("TCP", Protocol))
summary(Sept30th_TCP$Length)
summary(Sept30th_TCP$Info)
summary(Sept30th_TCP$Source)
summary(Sept30th_TCP$Destination)
Sept30th_ht_xm <- Sept30th %>% filter(grepl("HTTP/XML", Protocol))
summary(Sept30th_ht_xm$Length)
summary(Sept30th_ht_xm$Info)
summary(Sept30th_ht_xm$Source)
summary(Sept30th_ht_xm$Destination)
