library(leaps)
Mat <- subset(Stateful, select = c(Time, Length, Source.Port, Destination.Port, Window.size.value ))
regfit <- regsubsets(Length ~ ., Mat)
summary(regfit)
regsum <- summary(regfit)
plot(regsum$rsq,xlab = "Number of Variables", ylab = "Rsquare", type = "l")
plot(regsum$rss,xlab = "Number of Variables", ylab = "RSS", type = "l")
which.max(regsum$adjr2)
plot(regsum$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")
which.min(regsum$cp)
which.min(regsum$bic)
plot(regfit, scale = "r2")
plot(regfit, scale = "adjr2")
plot(regfit, scale = "Cp")
plot(regfit, scale = "bic")
#When Destination Port is the Response
regfit <- regsubsets(Destination.Port ~ ., Mat)
summary(regfit)
regsum <- summary(regfit)
plot(regsum$rsq,xlab = "Number of Variables", ylab = "Rsquare", type = "l")
plot(regsum$rss,xlab = "Number of Variables", ylab = "RSS", type = "l")
which.max(regsum$adjr2)
plot(regsum$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")
which.min(regsum$cp)
which.min(regsum$bic)
plot(regfit, scale = "r2")
plot(regfit, scale = "adjr2")
#when Source Port is the Response
regfit <- regsubsets(Source.Port ~ ., Mat)
summary(regfit)
regsum <- summary(regfit)
plot(regsum$rsq,xlab = "Number of Variables", ylab = "Rsquare", type = "l")
plot(regsum$rss,xlab = "Number of Variables", ylab = "RSS", type = "l")
which.max(regsum$adjr2)
plot(regsum$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")
which.min(regsum$cp)
which.min(regsum$bic)
plot(regfit, scale = "r2")
plot(regfit, scale = "Cp")
plot(regfit, scale = "bic")
# when time is the response variable
regfit <- regsubsets(Time ~ ., Mat)
summary(regfit)
regsum <- summary(regfit)
plot(regsum$rsq,xlab = "Number of Variables", ylab = "Rsquare", type = "l")
plot(regsum$rss,xlab = "Number of Variables", ylab = "RSS", type = "l")
which.max(regsum$adjr2)
plot(regsum$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")
which.min(regsum$cp)
which.min(regsum$bic)
plot(regfit, scale = "r2")
plot(regfit, scale = "Cp")
plot(regfit, scale = "bic")
# this indicates that Length is the best single predictor if other variables that cannot 
# predict on behalf of stateless protocols are taken out (numeric variables).  Length is not 
# as much of a factor when the response is Destination but that is the only time (as we are not
# able to record it as recieved) but still Time drops off before Length and length is predominant 
# every high BIC and residual squared result as well as next to lowest CP except when Length itself is the response variable